### PR TITLE
Docs: Update xref in reporter_overview.adoc

### PR DESCRIPTION
**Pull request by spmorrison**

### CODE REVIEW

**Review by sandbergja — CHANGES_REQUESTED** [review]
Thanks, @spmorrison !  When I tried this out, the link was still broken unfortunately.  I think the file extension needs to be `.adoc`, rather than `.html`.

**Comment by spmorrison** [comment]
Ah, sorry about that! I will fix the others I submitted.

**Review by sandbergja — APPROVED** [review]
Thanks, @spmorrison , it works for me now!

**Comment by sandbergja** [comment]
Thanks, @spmorrison !  Pushed to rel_3_13 and above.

**Pull request closed without merging**
