### PR TITLE
Docs: Configuring sign-on to OpenAthens

### PR DESCRIPTION
**Pull request by spmorrison**
Adding new page for OpenAthens configuration. Used documentation from 3.10 release notes, with the addition of a couple screenshots.

### CODE REVIEW

**Comment by abneiman** [comment]
Thanks Susan!

Two questions:
1) should Julian get an author credit as well, or are you the sole author?
2) confirming that the API key & other info in your openathens_record_editor.png screenshot is dummy info and not protected.

Also, note to future me or whomever commits this, there needs to be a new page entry in the local admin nav file pointing to openathens.adoc.

**Comment by spmorrison** [comment]
@abneiman ah yes! Julian should get author credit. I only changed a few things from what was written in the release notes. And yes, all the info in the screenshot is dummy info. Thanks!

**Comment by abneiman** [comment]
Thanks Susan! I'll try to get this in tomorrow or Monday.

**Comment by spmorrison** [comment]
Thanks so much.

**Pull request closed without merging**
