### PR TITLE
docs: adding a couple lines to keyboard shortcuts

### PR DESCRIPTION
**Pull request by abneiman**
Line 58 - adding a few words about using ? to bring up a list of webclient keyboard shortcuts

### CODE REVIEW

**Comment by sandbergja** [comment]
This looks good, with one issue: within the Angular client, the ? key doesn't work, but Ctrl+H does.  This seems like a little too much complexity to explain in the tips section.  Maybe we should hold off on merging this docs change until there is consistency between the two interfaces?

**Comment by abneiman** [comment]
Hmm, that is a tad too complex to explain in tips. I agree about holding off on merging this, but is there any value in filing a bug to bring the shortcuts into parity?

**Comment by sandbergja** [comment]
That sounds like a good next step to me.

**Comment by abneiman** [comment]
See bug here -- https://bugs.launchpad.net/evergreen/+bug/1842148

**Pull request closed without merging**
