### PR TITLE
Docs: Library settings editor, Hard Boundaries description

### PR DESCRIPTION
**Pull request by StephenGWills**
This was blank, now not.

### CODE REVIEW

**Comment by remocrevo** [comment]
Thanks @StephenGWills, this is great!  Would you add a git sign-off to your commit?  Or may I add one for you?

**Comment by StephenGWills** [comment]
> Thanks @StephenGWills, this is great! Would you add a git sign-off to your commit? Or may I add one for you?

By all means add a sign off and I'm not sure how to do that so if you have a link I can read that would be helpful.

**Comment by remocrevo** [comment]
You can add a sign-off line when you use "git commit" by simply adding the "-s" flag (which just adds a line of text to the commit message):
https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s

You may also need to tell git your user information first:
https://git-scm.com/docs/git-config#Documentation/git-config.txt-username

**Comment by StephenGWills** [comment]
Adding my info, I do see how one adds this except as a comment.
Signed-off-by: Stephen Wills swills@beyond-print.com

**Comment by sandbergja** [comment]
Thanks, @StephenGWills and @remocrevo -- sorry that this has sit for so long.  I updated your commit to fit the new antora version of the documentation, and included your signoff.  Pushed to 3.6 and above.

**Pull request closed without merging**
