### PR TITLE
Catalogue to catalog

### PR DESCRIPTION
**Pull request by katiegmartin**
changing catalogue to catalog in a variety of docs files

### CODE REVIEW

**Comment by katiegmartin** [comment]
https://bugs.launchpad.net/evergreen/+bug/1826256

**Comment by sandbergja** [comment]
Thanks, Katie!  I took the liberty of building antora with your proposed changes, and that can be found here: https://37-294141949-gh.circle-artifacts.com/0/docs-compiled/index.html

Also noting that there appear to be a handful of files that were added with a tilde as part of the filename -- maybe some backup files from a text editor.  We should remove those before merging your changes into Evergreen proper.

**Comment by katiegmartin** [comment]
Thanks Jane! I found two more 'catalogue's and have changed those and (I believe) removed all ~ files, can I trouble you to rebuild so I can check for our 'ue' friend again? :)

**Comment by sandbergja** [comment]
No problem!  Here it is: https://40-294141949-gh.circle-artifacts.com/0/docs-compiled/index.html

**Comment by katiegmartin** [comment]
Thanks Jane! This should be ready to be pushed to the master docs :)

**Comment by sandbergja** [comment]
Pushed to master and rel_3_6.  Thanks, Katie!

**Pull request closed without merging**
