### PR TITLE
Docs: Check in trigger hold cancel transit

### PR DESCRIPTION
**Pull request by dluchenbill**

### CODE REVIEW

**Comment by remocrevo** [comment]
@dluchenbill Thanks for this addition! If you have a chance, could you add italics or bold where you mention names of things?  I think I'd choose bold for actions (like "choose *Cancel Transit* from the Actions menu"), and italics for other named things (like "status of _Canceled Transit_ rather than _In Transit_").  What do you think?

**Comment by dluchenbill** [comment]
Yes, that's fine.  I updated the file, adding that formatting, and changing around a couple of the words for clarity.  Not sure if I need to make a new pull request or what?

**Comment by remocrevo** [comment]
Looks like your change is already included in this pull request.  Thanks!

**Comment by dluchenbill** [comment]
Excellent, thank you!

**Comment by sandbergja** [comment]
Thanks, @dluchenbill and @remocrevo .  Merged to rel_3_1, rel_3_2, rel_3_3, and master.  The spaces in the filename of the screenshot weren't working for me, so I took the liberty of renaming the file with no spaces.

**Pull request closed without merging**
