### PR TITLE
Docs: Updates for Describing your organization

### PR DESCRIPTION
**Pull request by spmorrison**
Here goes a first try at submitting documentation. I had to add the images after the fact, so hopefully they come through correctly. Please let me know if there are any issues. Thank you!

### CODE REVIEW

**Comment by spmorrison** [comment]
Hi @sandbergja thank you so much for reviewing this. When I try to add the image folder to docs/modules/admin_initial_setup/assets/images, it says uploads are disabled (screenshot attached). Is this something I would be able to get access to, or am I in the wrong spot? Thank you for your help!

Screenshot 2023-03-13 104910

**Comment by sandbergja** [comment]
Hi @spmorrison -- I think you're in slightly the wrong spot.  I think that was the spot to upload files to Evergreen directly, rather than to your branch.

To get to your branch, this pull request page should have a link near the top called "[spmorrison:smorrison/describing_your_organization](https://github.com/spmorrison/Evergreen/tree/smorrison/describing_your_organization)".  After clicking that link, you should be able to navigate to that directory and be able to upload again.  Let me know if this works or not!

**Comment by spmorrison** [comment]
Ah I see, that makes sense! I was able to upload to the branch, but please let me know if they're still not coming through correctly. I appreciate your help and patience with me. Thank you @sandbergja

**Comment by sandbergja** [comment]
Looks good to me!  Thanks, @spmorrison -- great first docs contribution!  I've pushed this to the 3.9 and above docs.

You should see the changes reflected within 24 hours at https://docs.evergreen-ils.org/.

**Comment by spmorrison** [comment]
Thank you so much!

**Pull request closed without merging**
