### PR TITLE
LP 1250528

### PR DESCRIPTION
**Pull request by katiegmartin**
change font size in browser

### CODE REVIEW

**Comment by katiegmartin** [comment]
second set of commits is for LP 1751146 Add tips for using the browser bookmarks toolbar in place of the XUL button bar

**Comment by sandbergja** [comment]
Thanks, Katie!  I took the liberty of building antora with your proposed changes, and that can be found here: https://38-294141949-gh.circle-artifacts.com/0/docs-compiled/index.html

Also noting that there appear to be a handful of files that were added with a tilde as part of the filename -- maybe some backup files from a text editor.  We should remove those before merging your changes into Evergreen proper.

**Comment by katiegmartin** [comment]
Thanks Jane! Those are from Vim & it was my first time using github desktop so all the interim files got uploaded. I have removed (all, I think, of) those and fixed an issue with toolbars-with-bookmarks-chrome.adoc - can I trouble you to rebuild?

**Comment by sandbergja** [comment]
Here you go: https://39-294141949-gh.circle-artifacts.com/0/docs-compiled/docs/latest/shared/about_this_documentation.html

**Comment by katiegmartin** [comment]
Thanks again Jane :) I was still having an issue with the include for one of the files in partial but I think I have it sorted, would you mind rebuilding? (& is that something I can learn to do? :))

**Comment by sandbergja** [comment]
Here ya go: https://43-294141949-gh.circle-artifacts.com/0/docs-compiled/index.html

FWIW: I have been using [this setup](https://bugs.launchpad.net/evergreen/+bug/1903476) to build these previews. Feedback definitely welcome there with the hope that we can get these builds to happen automatically some day. :-)

**Comment by sandbergja** [comment]
Sorry for the delay on this, @katiegmartin -- and thanks for these docs!  Merged to 3.6 and above.

**Pull request closed without merging**
