### PR TITLE
Docs: Update Best_Hold_Selection_Sort_Order.adoc

### PR DESCRIPTION
**Pull request by spmorrison**
Added additional BHSSO information from the following Evergreen conference presentation: https://docs.google.com/presentation/d/1iTDaNItUgD33ew57tPTipHEqwI7utxBy-6-jvBoORdE/edit#slide=id.gd947c15582_0_83

Writing credit goes to Angela Kilsdonk from Equinox.

Also added a couple new screenshots. Will upload a new folder of images with new naming conventions.

### CODE REVIEW

**Comment by abneiman** [comment]
Hi Susan - if you have the new images, I can merge this next week.

**Comment by spmorrison** [comment]
Thank you, Andrea! And apologies, I still can't seem to get the hang of GitHub. I submitted a separate pull request for the image folder here: https://github.com/spmorrison/Evergreen/pull/2 but am realizing that may not have gone to anyone. Attaching the images here as well.
bhsso_libsetting
create_new_bhsso
edit_bhsso
edit_selected_bhsso
new_bhsso

**Comment by abneiman** [comment]
No worries :) I'm not great at github, myself. Thanks for these, I will try to get them in today.

**Comment by abneiman** [comment]
Thanks Susan! This has been pushed to main and backported through rel_3_9

**Pull request closed without merging**
