### PR TITLE
update print templates to reflect new name

### PR DESCRIPTION
**Pull request by katiegmartin**
launchpad 1783387 - update receipt template editor documentation to reflect language change to "print templates" in web client
put both terms in index
updated title to Print (Receipt) Templates

### CODE REVIEW

**Comment by remocrevo** [comment]
Thanks for your work on this, Katie. One thing to note (and fix, if you want, otherwise I can later): Headers need underlines that match their length exactly. So the line just after the header that you changed needs 2 more dashes.  Does that make sense?

For the record, there's another style of AsciiDoc headers that uses prefixes (like "== Here's an H2", or "=== Here's an H3"), which doesn't suffer from this problem, but thus far most of our files use the underline notation, and DIG has agreed to not mix styles within each file.

**Comment by katiegmartin** [comment]
good catch! I remember talking about that at the hack a way but obviously didn't think of it when I changed that heading :-p 
I *think* I fixed it but i'm not very used to GitHub so please check.

**Comment by remocrevo** [comment]
Looks good now, thanks.

**Comment by sandbergja** [comment]
Thanks, @katiegmartin and @remocrevo.  I've squashed these into a single commit and add your change to master, rel_3_2, and rel_3_1.  This pull request can now be closed.

**Pull request closed without merging**
