### PR TITLE
Docs: review & update copy-to-item terminology changes

### PR DESCRIPTION
**Pull request by abneiman**
Reviewed Cheyenne's changes -- made a handful of minor typo fixes, added alt-tags where needed, and made some larger changes to the copy_tags_cataloging.adoc page to reflect the new language (including changing the page title, which I hope doesn't break anything).  I did update the references in root and root_cataloging to incorporate the new title info.

Signing off on Cheyenne's changes as edited by me.

### CODE REVIEW

**Comment by remocrevo** [comment]
This seems like a good time to add index terms for the old "copy" wording. Might be just a temporary need, but some people (like me) may be calling them "copy tags" for a while.

**Comment by abneiman** [comment]
Remington, that's a good point -- if I can grab a few minutes later this week I'll add index terms as appropriate.

**Comment by abneiman** [comment]
Commits added for index terms on the three pages I felt would benefit from them. PR ready for review!

**Comment by sandbergja** [comment]
Nice work, @Cheyenne-jones, @abneiman, and @remocrevo. I've pushed this to master, rel_3_3, and rel_3_2.

**Pull request closed without merging**
